### ISSUE TITLE
Use this in NextJS React App

### ISSUE THREAD

**Issue by iUnstable0** [jordienr/whatamesh#2]
How can I use this in my NextJS React app? I tried and it didn't work please help

**Comment by jordienr** [comment]
There's a guide at https://whatamesh.vercel.app/

**Comment by iUnstable0** [comment]
It doesn't work, my website is black white color with no errors
I did with the body element

**Comment by nezort11** [comment]
> How can I use this in my NextJS React app? I tried and it didn't work please help

```typescript
import { Gradient } from "../utils/Gradient/Gradient";

const gradient = new Gradient();

export default function Home() {
  useEffect(() => {
    gradient.initGradient("#rectangle-gradient1");
  }, []);

  return (
        // MUI
        <Box
          component="canvas"
          id="rectangle-gradient1"
          data-transition-in
          sx={{
            width: 400,
            height: 500,
            "--gradient-color-1": COLOR_ACCENT,
            "--gradient-color-2": COLOR_ACCENT2,
            "--gradient-color-3": COLOR_ACCENT3,
            "--gradient-color-4": COLOR_ACCENT4,
          }}
       />
  );
}
```

![image](https://user-images.githubusercontent.com/59317431/211801278-5eda0816-e252-4599-887e-6a3b931b8342.png)

**Comment by InsightfulFuture** [comment]
How can I do this without `mui` and with the `npm` package?

**Comment by iUnstable0** [comment]
> 

not sure what you mean by with the npm package, npm is a package manager not a package name lol

also, you don't have to do what he did, for me I imported the Gradient.js with ts-ignore (for typescript) and used canvas tag

**Comment by InsightfulFuture** [comment]
I got it to work after I posted that, forgot to reply. Also I meant the `whatamesh` npm package
