### ISSUE TITLE
Getting a TypeError with next v14.1.4

### ISSUE THREAD

**Issue by ZEUSGMJ** [jordienr/whatamesh#7]
Hey I'm trying to implement the gradient in an NextJs (App router) app. But I seem to be getting 

`TypeError: this.computedCanvasStyle is undefined`
```
app/Gradient.js (840:18) @ initGradientColors/this.sectionColors<

  838 | ]
  839 |   .map((cssPropertyName) => {
> 840 |     let hex = this.computedCanvasStyle
      |              ^
  841 |       .getPropertyValue(cssPropertyName)
  842 |       .trim();
  843 |     //Check if shorthand hex value was used and double the length so the conversion in normalizeColor will work
```

You can take a look at this [codebox](https://codesandbox.io/p/devbox/zealous-dan-8pzw8t?file=%2Fpackage.json&workspaceId=ebc9ec17-6de5-4ea0-85ed-981757cdb862).

Let me know if anything more is needed from my end.

**Comment by grahamplace** [comment]
I can't view your codebox, but it may be that you need to "use client". Here's a working demo using nextjs app router: [codebox](https://codesandbox.io/p/devbox/gradient-next-demo-xdrtx3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxrs2gm000073b6jfqz7j3qr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxrs2glz00023b6jooyo0ys2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxrs2glz00043b6j4oyg81r4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxrs2glz00063b6jzqf6s14m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxrs2glz00023b6jooyo0ys2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxrs2glz00013b6jahvevk3r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clxrs2glz00023b6jooyo0ys2%2522%252C%2522activeTabId%2522%253A%2522clxrs2glz00013b6jahvevk3r%2522%257D%252C%2522clxrs2glz00063b6jzqf6s14m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxrs2glz00053b6jab4jz3p7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxrs2glz00063b6jzqf6s14m%2522%252C%2522activeTabId%2522%253A%2522clxrs2glz00053b6jab4jz3p7%2522%257D%252C%2522clxrs2glz00043b6j4oyg81r4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxrs2glz00033b6jg915ptze%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clxrs2glz00043b6j4oyg81r4%2522%252C%2522activeTabId%2522%253A%2522clxrs2glz00033b6jg915ptze%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)


```
"use client";
import { useEffect } from "react";
import { Gradient } from "./Gradient.js";

export default function Home() {
  useEffect(() => {
    const gradient = new Gradient();
    gradient.initGradient("#gradient-canvas");
  }, []);

  return (
    <main>
      <canvas id="gradient-canvas" data-transition-in />
    </main>
  );
}
```

**Comment by ZEUSGMJ** [comment]
Hey @grahamplace, Thanks for the reply. 

I did use this approach, didn't work. But I installed the [whatamesh npm package](https://www.npmjs.com/package/whatamesh), and it works without any issue.
